//baseline-inf-net
python calculate_severity_score.py --input_dir ./Dataset/finalized_parenchyma_ictcf/parenchymas --parenchyma_input_dir ./Dataset/finalized_parenchyma_ictcf/parenchymas --csv_severity_file ./Dataset/finalized_parenchyma_ictcf/data.csv --save_segment_path ./segment_results/segments/baseline-inf-net/ --save_binary_segment_path ./segment_results/segments_original/baseline-inf-net --load_net_path ./Snapshots/save_weights/baseline-inf-net/Inf-Net-27.pth --load_multi_net_path ./Snapshots/save_weights/baseline-multi-inf-net/unet_model_58.pkl --save_multi_segment_path ./segment_results/multi_segments/baseline-multi-inf-net --save_binary_multi_segment_path ./segment_results/multi_segments_original/baseline-multi-inf-net --device cuda:1

// 04_random_cutout
python calculate_severity_score.py --input_dir ./Dataset/finalized_parenchyma_ictcf/parenchymas --parenchyma_input_dir ./Dataset/finalized_parenchyma_ictcf/parenchymas --csv_severity_file ./Dataset/finalized_parenchyma_ictcf/data.csv --save_segment_path ./segment_results/segments/inf-net04_random_cutout/ --save_binary_segment_path ./segment_results/segments_original/inf-net04_random_cutout --load_net_path ./Snapshots/save_weights/inf-net04_random_cutout/Inf-Net-369.pth --load_multi_net_path ./Snapshots/save_weights/multi-inf-net04_random_cutout/unet_model_67.pkl --save_multi_segment_path ./segment_results/multi_segments/multi-inf-net04_random_cutout --save_binary_multi_segment_path ./segment_results/multi_segments_original/multi-inf-net04_random_cutout --device cuda:1

// 05_random_cutout
python calculate_severity_score.py --input_dir ./Dataset/finalized_parenchyma_ictcf/parenchymas --parenchyma_input_dir ./Dataset/finalized_parenchyma_ictcf/parenchymas --csv_severity_file ./Dataset/finalized_parenchyma_ictcf/data.csv --save_segment_path ./segment_results/segments/inf-net05_random_cutout/ --save_binary_segment_path ./segment_results/segments_original/inf-net05_random_cutout --load_net_path ./Snapshots/save_weights/inf-net05_random_cutout/Inf-Net-40.pth --load_multi_net_path ./Snapshots/save_weights/multi-inf-net05_random_cutout/unet_model_54.pkl --save_multi_segment_path ./segment_results/multi_segments/multi-inf-net05_random_cutout --save_binary_multi_segment_path ./segment_results/multi_segments_original/multi-inf-net05_random_cutout --device cuda:1

// self-inf-net
python calculate_severity_score.py --input_dir ./Dataset/finalized_parenchyma_ictcf/parenchymas --parenchyma_input_dir ./Dataset/finalized_parenchyma_ictcf/parenchymas --csv_severity_file ./Dataset/finalized_parenchyma_ictcf/data.csv --save_segment_path ./segment_results/segments/self-inf-net/ --save_binary_segment_path ./segment_results/segments_original/self-inf-net --load_net_path ./Snapshots/save_weights/self-inf-net/Inf-Net-37.pth --load_multi_net_path ./Snapshots/save_weights/self-multi-inf-net/unet_model_406.pkl --save_multi_segment_path ./segment_results/multi_segments/self-multi-inf-net --save_binary_multi_segment_path ./segment_results/multi_segments_original/self-multi-inf-net --device cuda:1

// self-inf-net_improved
python calculate_severity_score.py --input_dir ./Dataset/finalized_parenchyma_ictcf/parenchymas --parenchyma_input_dir ./Dataset/finalized_parenchyma_ictcf/parenchymas --csv_severity_file ./Dataset/finalized_parenchyma_ictcf/data.csv --save_segment_path ./segment_results/segments/self-inf-net_improved/ --save_binary_segment_path ./segment_results/segments_original/self-inf-net_improved --load_net_path ./Snapshots/save_weights/self-inf-net_improved/Inf-Net-36.pth --load_multi_net_path ./Snapshots/save_weights/self-multi-inf-net_improved/unet_model_358.pkl --save_multi_segment_path ./segment_results/multi_segments/self-multi-inf-net_improved --save_binary_multi_segment_path ./segment_results/multi_segments_original/self-multi-inf-net_improved --device cuda:1